-- Add football stats columns to game_stats table
ALTER TABLE game_stats
  ADD COLUMN IF NOT EXISTS completions INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS pass_attempts INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS passing_yards INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS passing_tds INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS interceptions INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS passe_fumbles INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS sacks_taken INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS rush_attempts INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS rushing_yards INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS rushing_tds INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS rush_fumbles INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS receptions INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS targets INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS receiving_yards INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS receiving_tds INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS rec_fumbles INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS snaps INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS sacks_allowed INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS tackles INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS tackles_for_loss INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS defensive_sacks INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS hurries INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS safeties INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS def_interceptions INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS pass_breakups INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS receptions_allowed INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS targets_defended INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS yards_allowed INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS touchdowns_allowed INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS defensive_tds INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS forced_fumbles INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS fumble_recoveries INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS extra_points_made INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS extra_points_attempted INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS returns INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS return_yards INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS return_tds INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS return_fumbles INTEGER DEFAULT 0;

-- Note: field_goals_made and field_goals_attempted already exist in the schema
-- They are now used for kicking field goals in football

-- Add football-specific columns to players table
ALTER TABLE players
  ADD COLUMN IF NOT EXISTS jersey_number INTEGER,
  ADD COLUMN IF NOT EXISTS positions TEXT[] DEFAULT ARRAY[]::TEXT[];
